CORRECTION_REQUEST = "correctionRequest"
DELETE_REQUEST = "deleteRequest"
REGISTRATION_REQUEST = "registrationRequest"
REPLACE_REQUEST = "replaceRequest"
SOURCE_DOCUMENT = "sourceDocument"
XLINKHREF = "{http://www.w3.org/1999/xlink}href"
