backend_dev_poller:
	$(MAKE) -C src/backend dev_poller
backend_dev_dkc:
	$(MAKE) -C src/backend dev_dkc
db_dev:
	$(MAKE) -C src/backend dev_db
test:
	$(MAKE) -C src/backend test
dev_db_reset:
	$(MAKE) -C src/backend dev_db_reset
frontend_dev:
	$(MAKE) -C src/frontend dev_vue
migration_head:
	$(MAKE) -C src/backend dev_migration
dkc_bro_app:
	$(MAKE) -C src/backend app_dkc_bro
type_fix:
	$(MAKE) -C src/backend type_fix