"""Add enabled column to rule table

Revision ID: 330c2abd5329
Revises: 67d8be2c5bf9
Create Date: 2021-11-05 14:43:40.018921

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "330c2abd5329"
down_revision = "67d8be2c5bf9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rule", sa.Column("enabled", sa.Boolean(), nullable=True))
    op.execute("UPDATE rule SET enabled = true")
    op.alter_column("rule", "enabled", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rule", "enabled")
    # ### end Alembic commands ###
