"""Add org relation to batch and project

Revision ID: 8425795e6e2c
Revises: b3a93c859a55
Create Date: 2024-10-29 13:18:08.728382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8425795e6e2c'
down_revision = 'b3a93c859a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch', sa.Column('org_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'batch', 'organization', ['org_id'], ['id'])
    op.add_column('project', sa.Column('org_id', sa.Integer(), nullable=True))
    op.alter_column(
        'project',
        'timestamp',
        existing_type=postgresql.TIMESTAMP(),
        comment='Tijdstempel van het toegevoegde projectnummer',
        existing_comment='Tijdstempel van het projectnummer wat is toegevoegd',
        existing_nullable=True,
        existing_server_default=sa.text('now()')
    )
    op.create_foreign_key('fk_project_org_id', 'project', 'organization', ['org_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_project_org_id', 'project', type_='foreignkey')
    op.alter_column('project', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               comment='Tijdstempel van het projectnummer wat is toegevoegd',
               existing_comment='Tijdstempel van het toegevoegde projectnummer',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('project', 'org_id')
    op.drop_constraint(None, 'batch', type_='foreignkey')
    op.drop_column('batch', 'org_id')
    # ### end Alembic commands ###
