"""Save feedbackmessage under finding instead of rule

Revision ID: b15bfbaea59b
Revises: 6dd85657c2c4
Create Date: 2021-10-07 11:12:39.043604

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b15bfbaea59b"
down_revision = "6dd85657c2c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("finding", sa.Column("feedbackMessage", sa.String(), nullable=True))
    op.drop_column("rule", "feedbackMessage")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rule",
        sa.Column("feedbackMessage", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("finding", "feedbackMessage")
    # ### end Alembic commands ###
