"""add timestamp

Revision ID: b3a93c859a55
Revises: 8560f26e380a
Create Date: 2024-09-05 08:00:54.136741

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b3a93c859a55"
down_revision = "8560f26e380a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "processing_request",
        sa.Column(
            "timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("processing_request", "timestamp")
    # ### end Alembic commands ###
